### ISSUE TITLE
Fragment与Activity通信。

### ISSUE THREAD

**Issue by CuiTianci** [CherryLover/BlogTest#2]
看上去使用Navigation组件后，多个Fragment与外部Activity的联系只有一个NavHostFragment了，那么此时如何进行Fragment与Activity的通信呢？

**Comment by CherryLover** [comment]
不好意思，一直没看 issues，抱歉。

与 Activity 进行通信，无非就是打开时和已经打开。

从 Activity 中打开 Fragment 并携带数据：可以使用 Bundle 或是，Navigation 提供的 Safe-Args 插件（内部也是用的 Bundle）。

已经打开（当前处于 onResume 状态）的 Fragment 跟 Activity 进行通信的方法及优缺点：

1. 通过第三方的时间总线：eventBus、LiveEventBus、RxBus 等；
2. 自实现：
   1. 在 Activity 中利用 FragmentManager 获取到当前展示的 Fragment，然后调用 Fragment 的公共方法。
   2. 在 Fragment 的 onAttach 方法中，将 参数 Context 转换为具体的 Activity，然后在需要的时候可调用 Activity 的公共方法。

优缺点：

第一种方法，优点是耦合性较低，但是当发送的事件较多又没有对事件进行二次封装，就会显得繁杂。

第二种方法，缺点是只能针对特有的 Activity 或是 Fragment 使用，比如，一个 Fragment 可能展示两个或三个页面，区别仅仅是列表数据不同，这个时候会造成在 Fragment 中定义较多公开方法。优点是不依赖于任何第三方库。

个人建议：

如果项目中对事件总线（eventBus 等）有不错的事件封装，可以使用第一种，如果不想使用第三方库或是较少出现 Fragment 与 Activity 的情况可以使用第二种，或是某个 Activity 与 某个 Fragment 之间的通信实在较多也可以 用这个。

**Comment by CuiTianci** [comment]
感谢！ViewModel也不错。
